<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Injury extends Model
{
    use HasFactory;

    protected $fillable = [
        //'facility_id',
        'date_report',
        'lname',
        'fname',
        'mname',
        'suffix',

        'reported_by',
        'reporter_contactno',

        'oneiss_pno',
        'oneiss_status',
        'oneiss_dataentrystatus',
        'oneiss_patfacilityno',
        'oneiss_regno',
        'oneiss_tempregno',
        'hosp_no',
        'hosp_reg_no',
        'hosp_cas_no',

        //'registry_no',
        //'case_no',
        'patient_type',
        
        'sex',
        'bdate',
        'age_years',
        'age_months',
        'age_days',
        'perm_streetpurok',
        'perm_city_code',
        'perm_brgy_code',
        'tempaddress_sameasperm',

        'temp_streetpurok',
        'temp_city_code',
        'temp_brgy_code',

        'contact_no',
        'contact_no2',
        'philhealth',
        'injury_city_code',
        'injury_brgy_code',
        'injury_datetime',
        'consultation_datetime',
        'injury_intent',
        'vawc',
        'firstaid_given',
        'firstaid_type',
        'firstaid_bywho',
        'multiple_injuries',
        'abrasion',
        'abrasion_site',
        'avulsion',
        'avulsion_site',
        'burn',
        'burn_degree',
        'burn_site',
        'concussion',
        'concussion_site',
        'contusion',
        'contusion_site',
        'fracture',
        'fracture_open',
        'fracture_open_site',
        'fracture_closed',
        'fracture_closed_site',
        'open_wound',
        'open_wound_site',
        'traumatic_amputation',
        'traumatic_amputation_site',
        'others',
        'others_site',
        'bites_stings',
        'bites_stings_specify',
        'ext_burns',
        'ext_burns_type',
        'ext_burns_others_specify',
        'chemical_substance',
        'chemical_substance_specify',
        'contact_sharpobject',
        'contact_sharpobject_specify',
        'drowning',
        'drowning_type',
        'drowning_other_specify',
        'exposure_forcesofnature',
        'fall',
        'fall_specify',
        'firecracker',
        'firecracker_specify',
        'sexual_assault',
        'gunshot',
        'gunshot_specifyweapon',
        'hanging_strangulation',
        'mauling_assault',
        'transport_vehicular_accident',
        'ext_others',
        'ext_others_specify',
        'vehicle_type',
        'collision_type',
        'patients_vehicle_involved',
        'patients_vehicle_involved_others',
        'other_vehicle_involved',
        'other_vehicle_involved_others',
        'patient_position',
        'patient_position_others',
        'placeof_occurrence',
        'placeof_occurrence_workplace_specify',
        'placeof_occurrence_others_specify',
        'activitypatient_duringincident',
        'act_others',
        'otherrisk_factors',
        'oth_factors_specify',
        'safety',
        'safety_others',
        'transfer_hospital',
        'referred_hospital',
        'orig_hospital',
        'orig_physician',
        'status_reachingfacility',
        'ifalive_type',
        'modeof_transport',
        'modeof_transport_others',
        'initial_impression',
        'icd10_nature',
        'icd10_external',
        'disposition',
        'disposition_transferred',
        'outcome',
        'inp_completefinal_diagnosis',
        'inp_disposition',
        'inp_disposition_others',
        'inp_disposition_transferred',
        'inp_outcome',
        'inp_icd10_nature',
        'inp_icd10_external',
        'comments',
        'remarks',
        'qr',
        'created_by',
    ];
}
