<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class QesSub extends Model
{
    use HasFactory;
    
    protected $fillable = [
        'qes_main_id',
        'lname',
        'fname',
        'mname',
        'suffix',
        'age',
        'sex',
        'contact_number',
        'address_region_code',
        'address_region_text',
        'address_province_code',
        'address_province_text',
        'address_muncity_code',
        'address_muncity_text',
        'address_brgy_code',
        'address_brgy_text',
        'address_street',
        'address_houseno',
        'occupation',
        'placeof_work_school',

        'has_symptoms',
        'onset_datetime',
        'illness_duration',
        'diagnosis_date',
        'hospitalized',
        'admission_date',
        'discharge_date',
        'hospital_name',
        'outcome',
        'lbm_3xday',
        'fever',
        'nausea',
        'vomiting',
        'bodyweakness',
        'abdominalcramps',
        'rectalpain',
        'tenesmus',
        'bloodystool',
        'brownish',
        'yellowish',
        'greenish',
        'others',
        'others_specify',
        'volumeofstool',
        'quantify',
        'other_affected_names',
        'other_affected_ages',
        'other_affected_sex',
        'other_affected_donset',
        'question1',
        'question2',
        'question3',
        'question4',
        'question5',
        'question5_souce',
        'question5_others',
        'question6',
        'question6_source',
        'question7',
        'question7_others',
        'question8',
        'question9',
        'question10',
        'question11',
        'question12',
        'am_snacks_names',
        'am_snacks_datetime',
        'lunch_names',
        'lunch_datetime',
        'pm_snacks_names',
        'pm_snacks_datetime',
        'dinner_names',
        'dinner_datetime',
        'remarks',
    ];
}
