<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class RiskAssessmentForm extends Model
{
    use HasFactory;

    protected $fillable = [
        'link_opdrecord_id',
        'assessment_date',
        'lname',
        'fname',
        'mname',
        'suffix',
        'sex',
        'bdate',
        'street_purok',
        'address_brgy_code',
        'educational_attainment',
        
        'fh_hypertension',
        'fh_stroke',
        'fh_heartattack',
        'fh_diabetes',
        'fh_asthma',
        'fh_cancer',
        'fh_kidneydisease',
        'smoking',
        'alcohol_intake',
        'excessive_alcohol_intake',
        'obese',
        'overweight',
        'height',
        'weight',
        'central_adiposity',
        'waist_cm',
        'raised_bp',
        'systolic',
        'diastolic',
        'high_fatsalt_intake',
        'vegetable_serving',
        'fruits_serving',
        'physical_activity',
        'heart_attack',
        'question1',
        'question2',
        'question3',
        'question4',
        'question5',
        'question6',
        'question7',
        'stroke_ortia',
        'question8',
        'diabetes',
        'diabetes_medication',
        'polyphagia',
        'polydipsia',
        'polyuria',
        'raised_bloodglucose',
        'fbs_rbs',
        'fbs_rbs_date',
        'raised_bloodlipids',
        'cholesterol',
        'cholesterol_date',
        'urine_protein',
        'protein',
        'protein_date',
        'urine_ketones',
        'ketones',
        'ketones_date',
        'management',
        'meds',
        'date_followup',
        'risk_level',
        'finding',
        'assessed_by',
        'created_by',
        'facility_id',
    ];
}
